prompt: llmbar
vllm_args:
  model_args:
    model: /H1/zhouhongli/JudgePO/models/Vicuna-7B
    dtype: float16
    tensor_parallel_size: 1
    trust_remote_code: true
  sampling_params:
    temperature: 0
    max_tokens: 20
hf_args:
  model_args:
    model: meta-llama/Llama-2-7b-chat-hf
    dtype: float16
