prompt: llmbar
vllm_args:
  model_args:
    model: ../output/Mistral-7B-Instruct-v0.3-helpsteer2_et_lr_1e-6
    dtype: float16
    tensor_parallel_size: 1
    trust_remote_code: true
  sampling_params:
    temperature: 0
    max_tokens: 20
hf_args:
  model_args:
    model: mistralai/Mistral-7B-Instruct-v0.3
    dtype: float16
