prompt: judgelm
vllm_args:
  model_args:
    model: /root/autodl-tmp/models/Qwen3-14B
    dtype: float16
    tensor_parallel_size: 1
    trust_remote_code: true
  sampling_params:
    temperature: 0
    max_tokens: 20
hf_args:
  model_args:
    model: Qwen/Qwen3-14B
    dtype: float16
