### model
model_name_or_path: model/gemma-2b-it
### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset_dir: data
dataset: webgpt_et_gemma
template: gemma
cutoff_len: 1024
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: output/gemma-2b-it-webgpt_distilled_et_lr_2e-6_epoch_1
logging_steps: 1
save_steps: 1000
overwrite_output_dir: true

### train
per_device_train_batch_size: 8
gradient_accumulation_steps: 8
learning_rate: 2.0e-6
num_train_epochs: 1.0
lr_scheduler_type: cosine
warmup_ratio: 0.003
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.0
per_device_eval_batch_size: 1
eval_strategy: 'no'
eval_steps: 10
