### model
model_name_or_path: ../models/Mistral-7B-Instruct-v0.3
### method
stage: dpo
do_train: true
finetuning_type: full
pref_beta: 0.01
# simpo_gamma: 1.2
pref_loss: orpo  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset_dir: ../data
dataset: helpsteer2_dpo
template: mistral
cutoff_len: 1024
max_samples: 1000000
overwrite_cache: true

### output
output_dir: ../output/Mistral-7B-Instruct-v0.3-helpsteer2_orpo_0.01_lr_1e-5_epoch_3
logging_steps: 1
save_steps: 1000
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 1.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0
per_device_eval_batch_size: 1
eval_strategy: "no"
eval_steps: 500
