### model
model_name_or_path: /H1/zhouhongli/JudgePO/LLaMA-Factory/output/vicuna-7b-v1.5-helpsteer_simpo_2.5_1.6_lr_1e-5_epoch_3

### method
stage: sft
do_train: true
finetuning_type: full

### dataset
dataset_dir: train/LLaMA-Factory/data
dataset: helpsteer_et
template: vicuna
cutoff_len: 1024
max_samples: 100000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /H1/zhouhongli/JudgePO/LLaMA-Factory/output/vicuna-7b-v1.5-helpsteer_simpo_2.5_1.6_lr_1e-5_epoch_3_et
logging_steps: 1
save_steps: 1000
overwrite_output_dir: true

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 8
learning_rate: 2.0e-5
num_train_epochs: 3.0
lr_scheduler_type: cosine
warmup_ratio: 0.003
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.1
per_device_eval_batch_size: 1
eval_strategy: 'no'
eval_steps: 500
